#!/bin/bash
# 前端界面快速启动指南

echo "================================"
echo "  加密货币交易系统 - 前端界面"
echo "================================"
echo ""
echo "✅ 已完成的前端页面："
echo ""
echo "📄 页面列表："
echo "  1. auth.html              - 登录/注册页面"
echo "  2. main-dashboard.html     - 主仪表盘"
echo "  3. bots.html              - 机器人管理"
echo "  4. trading.html           - 实时交易监控"
echo "  5. analytics.html         - 数据分析"
echo "  6. settings.html          - 系统设置"
echo ""
echo "📊 页面大小："
ls -lh *.html | awk '{print "  " $9 " - " $5}'
echo ""
echo "================================"
echo "  快速开始指南"
echo "================================"
echo ""
echo "步骤1：启动后端服务"
echo "─────────────────"
echo "cd sirenkaifashiyong"
echo "python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"
echo ""
echo "步骤2：访问前端页面"
echo "─────────────────"
echo "打开浏览器，访问以下URL："
echo ""
echo "🔐 登录页面："
echo "   http://localhost:8000/static/auth.html"
echo ""
echo "📊 主仪表盘："
echo "   http://localhost:8000/static/main-dashboard.html"
echo ""
echo "🤖 机器人管理："
echo "   http://localhost:8000/static/bots.html"
echo ""
echo "📈 实时交易："
echo "   http://localhost:8000/static/trading.html"
echo ""
echo "📉 数据分析："
echo "   http://localhost:8000/static/analytics.html"
echo ""
echo "⚙️  系统设置："
echo "   http://localhost:8000/static/settings.html"
echo ""
echo "================================"
echo "  默认登录信息"
echo "================================"
echo ""
echo "用户名: admin"
echo "密码: admin123"
echo ""
echo "⚠️  重要提示："
echo "- 首次登录后请立即修改密码"
echo "- 确保后端服务正在运行"
echo "- 确保数据库已初始化"
echo ""
echo "================================"
echo "  技术栈"
echo "================================"
echo ""
echo "前端框架："
echo "  - HTML5"
echo "  - CSS3"
echo "  - JavaScript (ES6+)"
echo "  - Tailwind CSS"
echo ""
echo "第三方库："
echo "  - Chart.js (图表)"
echo "  - Axios (HTTP请求)"
echo "  - Bootstrap 5 (部分组件)"
echo ""
echo "设计风格："
echo "  - 现代简约"
echo "  - 响应式设计"
echo "  - 渐变主题"
echo "  - 暗色主题（交易页面）"
echo ""
echo "================================"
echo "  功能特性"
echo "================================"
echo ""
echo "✅ 已完成："
echo "  - 用户认证（登录/注册）"
echo "  - 主仪表盘（统计+图表）"
echo "  - 机器人管理（CRUD操作）"
echo "  - 实时交易监控（K线+深度）"
echo "  - 数据分析（图表+表格）"
echo "  - 系统设置（用户+API+通知）"
echo ""
echo "📱 移动端适配："
echo "  - 响应式布局"
echo "  - 触摸友好"
echo "  - 移动端优化"
echo ""
echo "🔗 实时功能："
echo "  - WebSocket连接"
echo "  - 实时价格更新"
echo "  - 实时订单推送"
echo "  - 自动重连机制"
echo ""
echo "📊 数据可视化："
echo "  - K线图（多周期）"
echo "  - 深度图"
echo "  - 趋势图"
echo "  - 统计图"
echo "  - 饼图"
echo ""
echo "================================"
echo "  常见问题"
echo "================================"
echo ""
echo "Q: 页面无法访问？"
echo "A: 检查后端服务是否启动："
echo "   python -m uvicorn app.main:app --reload"
echo ""
echo "Q: 登录失败？"
echo "A: 1. 检查数据库是否初始化：python init_db.py"
echo "   2. 检查用户名密码是否正确"
echo "   3. 查看浏览器控制台错误"
echo ""
echo "Q: 数据不更新？"
echo "A: 1. 检查WebSocket连接状态"
echo "   2. 查看网络请求"
echo "   3. 检查后端API是否正常"
echo ""
echo "Q: 图表不显示？"
echo "A: 1. 检查网络连接（CDN加载）"
echo "   2. 查看浏览器控制台"
echo "   3. 检查数据格式"
echo ""
echo "================================"
echo "  下一步"
echo "================================"
echo ""
echo "📚 查看文档："
echo "  - 前端UI指南: static/FRONTEND_UI_GUIDE.md"
echo "  - API文档: docs/API_DOCUMENTATION.md"
echo "  - 快速开始: QUICKSTART.md"
echo ""
echo "🚀 开始开发："
echo "  1. 启动后端服务"
echo "  2. 打开浏览器访问页面"
echo "  3. 使用默认账户登录"
echo "  4. 开始使用系统"
echo ""
echo "================================"
